theme: jekyll-theme-minimal
title: Rob McQueen's Homepage
description: Rob McQueen is a graduate student in Boston College's Philosophy Department

github:
  is_project_page: false
  is_user_page: false
